SELECT CONCAT(NAME,CONCAT('(',CONCAT(SUBSTR(OCCUPATION,1,1),')')))
FROM OCCUPATIONS ORDER BY NAME;
SELECT CONCAT('There are a total of',CONCAT(' ',CONCAT(COUNT(OCCUPATION),CONCAT(' ',CONCAT(LOWER(OCCUPATION),'s.')))))
AS TOTAL FROM OCCUPATIONS 
GROUP BY OCCUPATION
ORDER BY TOTAL;